# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "vivasoft-popup"
client_id = "f376625ebfebab6d810ed5570b98b6e2"
application_url = "https://timer-recordings-authority-barry.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes,read_script_tags,write_script_tags"

[auth]
redirect_urls = [
  "https://timer-recordings-authority-barry.trycloudflare.com/auth/callback",
  "https://timer-recordings-authority-barry.trycloudflare.com/auth/shopify/callback",
  "https://timer-recordings-authority-barry.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "fusionfirm.myshopify.com"
